# Generated by Django 5.0.6 on 2024-05-11 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mood_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='mood_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='place_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=30)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('mood_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.mood_tag')),
                ('place_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.place_tag')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100000)),
                ('photo', models.ImageField(upload_to='')),
                ('mood_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.mood_status')),
                ('mood_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.mood_tag')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.place')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
