# Generated by Django 5.0.6 on 2024-05-11 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_place_photo_alter_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='explanation',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_tag',
            field=models.CharField(choices=[('1', '나무가 울창한'), ('2', '쾌적한 실내'), ('3', '여러명'), ('4', '나홀로'), ('5', '조용한'), ('6', '인기')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.place'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
